// Модель образовательных маршрутов РУСАЛЕН · v11 (визуальные связи)
// programs: программы; MODULES: учебные блоки; programs: связи «программа:роль»
// роль required — обязательный блок, choice — вариативная ветвь.

export const PROGRAMS = [
  { id: 'P01', name: 'Клинические аспекты в деятельности психолога', short: 'Клин. аспекты', formatCode: 'ПК', total: 144 },
  { id: 'P02', name: 'КПТ', short: 'КПТ', formatCode: 'ПК', total: 108 },
  { id: 'P03', name: 'Гипноз', short: 'Гипноз', formatCode: 'ПК', total: 108 },
  { id: 'P04', name: 'Трансперсональная психотерапия', short: 'Трансперс.', formatCode: 'ПК', total: 144 },
  { id: 'P05', name: 'ПФК', short: 'ПФК', formatCode: 'ПП', total: 510 },
  { id: 'P06', name: 'Последствия стресса и психотравмы', short: 'Стресс и травма', formatCode: 'ПП', total: 328 },
  { id: 'P07', name: 'Сексология', short: 'Сексология', formatCode: 'ПП', total: 600 },
  { id: 'P08', name: 'Аддиктология', short: 'Аддиктология', formatCode: 'ПП', total: 316 },
  { id: 'P09', name: 'Психообразование', short: 'Психообраз.', formatCode: 'ПК', total: 36 },
  { id: 'P10', name: 'Метакогнитивный тренинг', short: 'МКТ', formatCode: 'ПК', total: 48 },
];

export const AREA_ORDER = [
  'КЛИНИЧЕСКИЕ АСПЕКТЫ',
  'ПСИХОТЕРАПИЯ',
  'ОБЩИЕ МОДУЛИ',
  'ПФК',
  'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ',
  'СЕКСОЛОГИЯ',
  'АДДИКТОЛОГИЯ',
  'ПСИХООБРАЗОВАНИЕ',
  'МЕТАКОГНИТИВНЫЙ ТРЕНИНГ',
];

export const MODULES = [
  { id: 'psyphys', code: 'M01', label: 'Психофизиология: активность, ТФС и системное понимание человека', area: 'КЛИНИЧЕСКИЕ АСПЕКТЫ', hours: 24, programs: ['P01:required', 'P05:required', 'P06:required', 'P07:required', 'P08:required'] },
  { id: 'science', code: 'M02', label: 'Научное, критическое и психотерапевтическое мышление', area: 'КЛИНИЧЕСКИЕ АСПЕКТЫ', hours: 12, programs: ['P01:required', 'P02:required', 'P03:required', 'P04:required', 'P05:required', 'P06:required', 'P07:required', 'P08:required'] },
  { id: 'ethics', code: 'M03', label: 'Этика и профессиональные границы', area: 'КЛИНИЧЕСКИЕ АСПЕКТЫ', hours: 8, programs: ['P01:required', 'P02:required', 'P03:required', 'P04:required', 'P05:required', 'P06:required', 'P07:required', 'P08:required'] },
  { id: 'interview', code: 'M04', label: 'Клиническое интервью', area: 'КЛИНИЧЕСКИЕ АСПЕКТЫ', hours: 16, programs: ['P01:required', 'P02:required', 'P03:required', 'P04:required', 'P05:required', 'P06:required', 'P07:required', 'P08:required'] },
  { id: 'psychiatry', code: 'M05', label: 'Психиатрия для психологов', area: 'КЛИНИЧЕСКИЕ АСПЕКТЫ', hours: 24, programs: ['P01:required', 'P06:required', 'P07:required', 'P08:required'] },
  { id: 'neurology', code: 'M06', label: 'Неврология для психологов', area: 'КЛИНИЧЕСКИЕ АСПЕКТЫ', hours: 16, programs: ['P01:required', 'P06:required', 'P07:required', 'P08:required'] },
  { id: 'endocrine', code: 'M07', label: 'Эндокринология для психологов', area: 'КЛИНИЧЕСКИЕ АСПЕКТЫ', hours: 12, programs: ['P01:required', 'P06:required', 'P07:required', 'P08:required'] },
  { id: 'ddx', code: 'M08', label: 'Дифференциальная диагностика и интегральная формулировка случая', area: 'КЛИНИЧЕСКИЕ АСПЕКТЫ', hours: 32, programs: ['P01:required', 'P06:required', 'P07:required', 'P08:required'] },
  { id: 'cbt1', code: 'M10', label: 'КПТ I: основы КПТ', area: 'ПСИХОТЕРАПИЯ', hours: 36, programs: ['P02:required'] },
  { id: 'cbt2', code: 'M11', label: 'КПТ II: волны и направления КПТ психотерапии', area: 'ПСИХОТЕРАПИЯ', hours: 36, programs: ['P02:required'] },
  { id: 'hyptherapy', code: 'M12', label: 'Психотерапевтический гипноз', area: 'ПСИХОТЕРАПИЯ', hours: 48, programs: ['P03:required'] },
  { id: 'trbase', code: 'M14', label: 'Трансперсональная психотерапия', area: 'ПСИХОТЕРАПИЯ', hours: 36, programs: ['P04:required'] },
  { id: 'breath', code: 'M15', label: 'Дыхательные практики', area: 'ПСИХОТЕРАПИЯ', hours: 24, programs: ['P04:required', 'P05:required'] },
  { id: 'holo', code: 'M16', label: 'Холотропное дыхание', area: 'ПСИХОТЕРАПИЯ', hours: 48, programs: ['P04:required'] },
  { id: 'hypbase', code: 'M13', label: 'Основы гипноза', area: 'ОБЩИЕ МОДУЛИ', hours: 24, programs: ['P03:required', 'P05:required'] },
  { id: 'pfctheory', code: 'M17', label: 'Теория психофизиологической коррекции', area: 'ПФК', hours: 48, programs: ['P05:required'] },
  { id: 'pfcassess', code: 'M18', label: 'Функциональная оценка состояния и выбор мишеней', area: 'ПФК', hours: 32, programs: ['P05:required'] },
  { id: 'bfb', code: 'M19', label: 'Биологическая обратная связь (БОС)', area: 'ПФК', hours: 72, programs: ['P05:required'] },
  { id: 'auto', code: 'M20', label: 'Аутогенные практики', area: 'ПФК', hours: 32, programs: ['P05:required'] },
  { id: 'body', code: 'M21', label: 'Телесные, двигательные и кинезиологические методы', area: 'ПФК', hours: 56, programs: ['P05:required'] },
  { id: 'hyppfc', code: 'M22', label: 'Гипноз как психофизиологическая коррекция', area: 'ПФК', hours: 48, programs: ['P05:required'] },
  { id: 'pfcint', code: 'M23', label: 'Интеграция методов ПФК', area: 'ПФК', hours: 34, programs: ['P05:required'] },
  { id: 'pfcpractice', code: 'M24', label: 'Практикум ПФК', area: 'ПФК', hours: 80, programs: ['P05:required'] },
  { id: 'str1', code: 'M25', label: 'Стресс и адаптация', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 16, programs: ['P06:required'] },
  { id: 'str2', code: 'M26', label: 'Острые последствия стрессовых воздействий', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 16, programs: ['P06:required'] },
  { id: 'str3', code: 'M27', label: 'Хронический и накопленный стресс', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 16, programs: ['P06:required'] },
  { id: 'str4', code: 'M28', label: 'Психологическая травма', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 24, programs: ['P06:required'] },
  { id: 'str5', code: 'M29', label: 'Ранняя и довербальная травма', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 16, programs: ['P06:required'] },
  { id: 'strint', code: 'M30', label: 'Интервью при последствиях стресса', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 12, programs: ['P06:required'] },
  { id: 'strddx', code: 'M31', label: 'Дифференциальная диагностика стресс-ассоциированных состояний', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 16, programs: ['P06:required'] },
  { id: 'strhelp', code: 'M32', label: 'Консультативная помощь при последствиях стресса', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 24, programs: ['P06:required'] },
  { id: 'strprev', code: 'M33', label: 'Профилактика хронизации', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 12, programs: ['P06:required'] },
  { id: 'strrec', code: 'M34', label: 'Восстановление и ресурсы', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 16, programs: ['P06:required'] },
  { id: 'strcase', code: 'M35', label: 'Интеграция стрессового случая', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 16, programs: ['P06:required'] },
  { id: 'cbtstr', code: 'M36', label: 'КПТ при последствиях стресса', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 24, programs: ['P02:choice', 'P06:choice'] },
  { id: 'hypstr', code: 'M37', label: 'Гипноз при последствиях стресса', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 24, programs: ['P03:choice', 'P06:choice'] },
  { id: 'pfcstr', code: 'M38', label: 'ПФК при стрессовой дизрегуляции', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 24, programs: ['P05:choice', 'P06:choice'] },
  { id: 'trstr', code: 'M68', label: 'Трансперсональная психотерапия при последствиях стресса и психотравмы', area: 'ПОСЛЕДСТВИЯ СТРЕССА И ПСИХОТРАВМЫ', hours: 24, programs: ['P04:choice', 'P06:choice'] },
  { id: 'sex1', code: 'M39', label: 'Психология сексуальности и сексуальное здоровье', area: 'СЕКСОЛОГИЯ', hours: 60, programs: ['P07:required'] },
  { id: 'sex2', code: 'M40', label: 'Психофизиология сексуальности', area: 'СЕКСОЛОГИЯ', hours: 48, programs: ['P07:required'] },
  { id: 'sexrel', code: 'M41', label: 'Отношения и сексуальность пары', area: 'СЕКСОЛОГИЯ', hours: 48, programs: ['P07:required'] },
  { id: 'sextr', code: 'M42', label: 'Сексуальная травма', area: 'СЕКСОЛОГИЯ', hours: 60, programs: ['P07:required'] },
  { id: 'sexcons', code: 'M43', label: 'Психологическое консультирование в сексологии', area: 'СЕКСОЛОГИЯ', hours: 72, programs: ['P07:required'] },
  { id: 'sexmed', code: 'M44', label: 'Медицинские аспекты сексологии', area: 'СЕКСОЛОГИЯ', hours: 48, programs: ['P07:required'] },
  { id: 'sexint', code: 'M45', label: 'Тонкости интервью в сексологии', area: 'СЕКСОЛОГИЯ', hours: 36, programs: ['P07:required'] },
  { id: 'sexddx', code: 'M46', label: 'Дифференциальная диагностика в сексологии', area: 'СЕКСОЛОГИЯ', hours: 48, programs: ['P07:required'] },
  { id: 'sexcase', code: 'M47', label: 'Интеграция сексологического случая', area: 'СЕКСОЛОГИЯ', hours: 36, programs: ['P07:required'] },
  { id: 'cbtsex', code: 'M48', label: 'КПТ в сексологии', area: 'СЕКСОЛОГИЯ', hours: 24, programs: ['P02:choice', 'P07:choice'] },
  { id: 'hypsex', code: 'M49', label: 'Гипноз в сексологической практике', area: 'СЕКСОЛОГИЯ', hours: 24, programs: ['P03:choice', 'P07:choice'] },
  { id: 'pfcsex', code: 'M50', label: 'ПФК в сексологии', area: 'СЕКСОЛОГИЯ', hours: 24, programs: ['P05:choice', 'P07:choice'] },
  { id: 'trsex', code: 'M69', label: 'Трансперсональная психотерапия в сексологии', area: 'СЕКСОЛОГИЯ', hours: 24, programs: ['P04:choice', 'P07:choice'] },
  { id: 'add1', code: 'M51', label: 'Теории зависимости и аддиктивного поведения', area: 'АДДИКТОЛОГИЯ', hours: 24, programs: ['P08:required'] },
  { id: 'addtypes', code: 'M52', label: 'Химические и нехимические зависимости', area: 'АДДИКТОЛОГИЯ', hours: 32, programs: ['P08:required'] },
  { id: 'add6', code: 'M56', label: 'Мотивация и изменение поведения', area: 'АДДИКТОЛОГИЯ', hours: 24, programs: ['P08:required'] },
  { id: 'add8', code: 'M58', label: 'Профилактика рецидива', area: 'АДДИКТОЛОГИЯ', hours: 16, programs: ['P08:required'] },
  { id: 'add9', code: 'M59', label: 'Семья, реабилитация и социальное восстановление', area: 'АДДИКТОЛОГИЯ', hours: 24, programs: ['P08:required'] },
  { id: 'addint', code: 'M61', label: 'Интервью при зависимом поведении', area: 'АДДИКТОЛОГИЯ', hours: 12, programs: ['P08:required'] },
  { id: 'addddx', code: 'M62', label: 'Дифференциальная диагностика зависимостей', area: 'АДДИКТОЛОГИЯ', hours: 24, programs: ['P08:required'] },
  { id: 'cbtadd', code: 'M63', label: 'КПТ в аддиктологии', area: 'АДДИКТОЛОГИЯ', hours: 24, programs: ['P02:choice', 'P08:choice'] },
  { id: 'addcase', code: 'M64', label: 'Интеграция аддиктологического случая', area: 'АДДИКТОЛОГИЯ', hours: 16, programs: ['P08:required'] },
  { id: 'hypadd', code: 'M67', label: 'Гипноз в аддиктологии', area: 'АДДИКТОЛОГИЯ', hours: 24, programs: ['P03:choice', 'P08:choice'] },
  { id: 'tradd', code: 'M70', label: 'Трансперсональная психотерапия в аддиктологии', area: 'АДДИКТОЛОГИЯ', hours: 24, programs: ['P04:choice', 'P08:choice'] },
  { id: 'pfcadd', code: 'M71', label: 'ПФК в аддиктологии', area: 'АДДИКТОЛОГИЯ', hours: 24, programs: ['P05:choice', 'P08:choice'] },
  { id: 'psychoed', code: 'M65', label: 'Психообразование', area: 'ПСИХООБРАЗОВАНИЕ', hours: 36, programs: ['P09:required'] },
  { id: 'mct', code: 'M66', label: 'Метакогнитивный тренинг', area: 'МЕТАКОГНИТИВНЫЙ ТРЕНИНГ', hours: 48, programs: ['P10:required'] },
];